# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fed.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fed.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tfed.proto\x12\x03\x66\x65\x64\"\xb0\x01\n\x0eTrainingConfig\x12\x13\n\x0bnum_clients\x18\x01 \x01(\x05\x12\x14\n\x0ctotal_rounds\x18\x02 \x01(\x05\x12\x14\n\x0clocal_epochs\x18\x03 \x01(\x05\x12\x12\n\nbatch_size\x18\x04 \x01(\x05\x12\n\n\x02lr\x18\x05 \x01(\x02\x12\x10\n\x08momentum\x18\x06 \x01(\x02\x12\x17\n\x0fsample_fraction\x18\x07 \x01(\x02\x12\x12\n\nmodel_name\x18\x08 \x01(\t\"&\n\x0fRegisterRequest\x12\x13\n\x0b\x63lient_name\x18\x01 \x01(\t\"r\n\rRegisterReply\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63lient_index\x18\x02 \x01(\x05\x12\x13\n\x0bgroup_index\x18\x03 \x01(\x05\x12#\n\x06\x63onfig\x18\x04 \x01(\x0b\x32\x13.fed.TrainingConfig\"#\n\x0eGetTaskRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"j\n\tTaskReply\x12\r\n\x05round\x18\x01 \x01(\x05\x12\x13\n\x0bparticipate\x18\x02 \x01(\x08\x12\x14\n\x0cglobal_model\x18\x03 \x01(\x0c\x12#\n\x06\x63onfig\x18\x04 \x01(\x0b\x32\x13.fed.TrainingConfig\"\x85\x02\n\rUploadRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x10\n\x08group_id\x18\x02 \x01(\x05\x12\r\n\x05round\x18\x03 \x01(\x05\x12\x13\n\x0blocal_model\x18\x04 \x01(\x0c\x12\x13\n\x0bnum_samples\x18\x05 \x01(\x03\x12\x17\n\ntrain_loss\x18\x06 \x01(\x01H\x00\x88\x01\x01\x12\x16\n\ttrain_acc\x18\x07 \x01(\x01H\x01\x88\x01\x01\x12\x16\n\ttest_loss\x18\x08 \x01(\x01H\x02\x88\x01\x01\x12\x15\n\x08test_acc\x18\t \x01(\x01H\x03\x88\x01\x01\x42\r\n\x0b_train_lossB\x0c\n\n_train_accB\x0c\n\n_test_lossB\x0b\n\t_test_acc\".\n\x0bUploadReply\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\r\n\x05round\x18\x02 \x01(\x05\x32\xb4\x01\n\x10\x46\x65\x64\x65ratedService\x12:\n\x0eRegisterClient\x12\x14.fed.RegisterRequest\x1a\x12.fed.RegisterReply\x12.\n\x07GetTask\x12\x13.fed.GetTaskRequest\x1a\x0e.fed.TaskReply\x12\x34\n\x0cUploadUpdate\x12\x12.fed.UploadRequest\x1a\x10.fed.UploadReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fed_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRAININGCONFIG']._serialized_start=19
  _globals['_TRAININGCONFIG']._serialized_end=195
  _globals['_REGISTERREQUEST']._serialized_start=197
  _globals['_REGISTERREQUEST']._serialized_end=235
  _globals['_REGISTERREPLY']._serialized_start=237
  _globals['_REGISTERREPLY']._serialized_end=351
  _globals['_GETTASKREQUEST']._serialized_start=353
  _globals['_GETTASKREQUEST']._serialized_end=388
  _globals['_TASKREPLY']._serialized_start=390
  _globals['_TASKREPLY']._serialized_end=496
  _globals['_UPLOADREQUEST']._serialized_start=499
  _globals['_UPLOADREQUEST']._serialized_end=760
  _globals['_UPLOADREPLY']._serialized_start=762
  _globals['_UPLOADREPLY']._serialized_end=808
  _globals['_FEDERATEDSERVICE']._serialized_start=811
  _globals['_FEDERATEDSERVICE']._serialized_end=991
# @@protoc_insertion_point(module_scope)
