_wandb:
    value:
        cli_version: 0.21.4
        e:
            xp7jgr5ohg2zd3eii6ith091buiv40z4:
                args:
                    - --bind
                    - 0.0.0.0:50052
                    - --data_root
                    - /home/liaoyangxu/FedKTL/dataset
                    - --dataset_name
                    - Cifar10
                    - --num_classes
                    - "10"
                    - --num_clients
                    - "20"
                    - --rounds
                    - "3"
                    - --local_epochs
                    - "1"
                    - --batch_size
                    - "64"
                    - --lr
                    - "0.005"
                    - --momentum
                    - "0.9"
                    - --sample_fraction
                    - "1.0"
                    - --seed
                    - "42"
                    - --model_name
                    - resnet18
                    - --max_message_mb
                    - "128"
                    - --feature_dim
                    - "512"
                    - --encoder_ratio
                    - "0.7"
                    - --algorithm
                    - FedEXT
                    - --run_dir
                    - /home/liaoyangxu/FedKTL/FedReal/runs/Cifar10/FedEXT/20250927_014925
                    - --device
                    - cuda
                    - --use_wandb
                    - --wandb_project
                    - fedreal
                    - --wandb_run_name
                    - fedreal-20250927_014925
                cpu_count: 36
                cpu_count_logical: 72
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "943412031488"
                        used: "866409951232"
                email: epicmocn@gmail.com
                executable: /home/liaoyangxu/miniconda3/envs/htfllib/bin/python
                git:
                    commit: 5860378705d0cdefe4cd2ea445ddcef443f0121d
                    remote: https://github.com/liaosunny123/FedKKTTLL.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-de27ef82-cf7b-fd4f-0333-b6979bef67de
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-a0864ec4-2933-57ec-0deb-48f22265ec89
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-92a53f0c-0e5c-b814-e1f4-7c21055741d1
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-2ab4065b-2df1-1c28-e60d-1a8a9b429a62
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-fc01883c-698b-1b34-16bb-1a442021d8d6
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-5d0e016e-7a28-268b-6674-a7af10ed0cc4
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-085356dd-7de6-b7de-77b5-cc01c226773c
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-0c41e50c-0ed3-ae1f-8d94-7159903066c3
                host: user-ESC8000-G4
                memory:
                    total: "270041579520"
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.31
                program: -m server.server_main
                python: CPython 3.11.13
                root: /home/liaoyangxu/FedKTL/FedReal
                startedAt: "2025-09-26T17:49:31.772820Z"
                writerId: xp7jgr5ohg2zd3eii6ith091buiv40z4
        m:
            - "1": Global/step
              "6":
                - 3
              "7": []
            - "2": Client/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 7
                - 13
                - 16
                - 61
                - 62
            "4": 3.11.13
            "5": 0.21.4
            "10":
                - 20
            "12": 0.21.4
            "13": linux-x86_64
algorithm:
    value: FedEXT
batch_size:
    value: 64
dataset:
    value: Cifar10
encoder_ratio:
    value: 0.7
feature_dim:
    value: 512
local_epochs:
    value: 1
lr:
    value: 0.005
model_name:
    value: resnet18
momentum:
    value: 0.9
num_clients:
    value: 20
rounds:
    value: 3
sample_fraction:
    value: 1
